### ISSUE TITLE
Mod3 + "o" (Neo) strange behavior in browsers

### ISSUE THREAD

**Issue by neominik** [jgosmann/Karabiner-Elements-Neo#10]
Mod3 + "o" (Neo) doesn't insert "*" in text-fields on some web-pages but takes one a page back in history.

**Comment by jgosmann** [comment]
Can you specific about the browser in which you observed that and which mod3 key you were using?

**Comment by neominik** [comment]
I have tried Safari and Chrome both the same behaviour with both Mod3 keys (Caps-Lock and #).
In text-fields on GitHub it strangely works as intended though. I'm using the keymap from the neo-layout page if that helps. Maybe I'm gonna try the one you provided.

**Comment by jgosmann** [comment]
Weird, I will see if I can reproduce it this evening (EST).

**Comment by jgosmann** [comment]
I can't seem to reproduce this. 😕

**Comment by neominik** [comment]
Hmm weird. Any way for me to debug this? The Karabiner Event-Viewer says the following when I press '*':
```
eventType:FlagsChanged    code:0x3d       name:right_option    flags:Opt                                misc:characters:    
eventType:KeyDown         code:0x5        name:g               flags:Opt                                misc:characters:    
eventType:KeyUp           code:0x5        name:g               flags:Opt                                misc:characters:    
eventType:FlagsChanged    code:0x3d       name:right_option    flags:                                   misc:characters:
```

**Comment by jgosmann** [comment]
That is the expected output. I think the problem is not with Karabiner, but the `neo.keylayout`.

**Comment by neominik** [comment]
I tried both neo.keylayout files now (with a reboot in between). they show the same behaviour.
A specific page where * doesn't work is the code editor of codecademy.com. And I had the same problem with other online code editors.

**Comment by tjanson** [comment]
For the record, I can’t reproduce it either. Do you happen to have a keyboard with an actual numpad? Then you could test whether that has the same effect.

**Comment by olbrichj** [comment]
codecademy.com had those problems already with prior versions of karabiner. So I guess it's somewhere in their js-editor code which handles the mapping incorrectly

**Comment by jgosmann** [comment]
This seems to be nothing I can fix in Karabiner-Elements or neo2-layout-osx, it is probably as issue with the browser or JS application. I added a note to the known issues section of the readme about this.
