### ISSUE TITLE
Strange issue with Ergodox

### ISSUE THREAD

**Issue by julasamer** [jgosmann/Karabiner-Elements-Neo#11]
I use an ergodox keyboard. I have a certain key setup to emit the "<" key, the same key that is used for mod4 on the internal keyboard (i.e. when Karabiner Elements is quit, both the mod4 keys print "<" in a text editor). 
However, when I launch Karabiner Elements (Neo), layer 4 works on the internal keyboard, but on the ergodox the mod4 key just emits "^" (i.e. layer 4 does not work).

Any ideas on how to fix this?

**Comment by jgosmann** [comment]
Karabiner is doing the remapping of keys on the layer of key codes corresponding to physical keys transmitted via USB. It sounds like the ergodox keyboard also does some remapping (“certain key setup to emit ...”) itself which might interfere or get keys remapped by Karabiner while expecting the unremapped keys.

Can you setup your mod4 keys to emit right cmd?

**Comment by tjanson** [comment]
This may actually be the same issue as #15: (Left?) M4 not working on external keyboards.

**Comment by jgosmann** [comment]
As @tjanson pointed out this might be similar to #15, i.e. you might be able to solve this issue to configure the correct remapping in Karabiner-Elements. You can check with Karabiner-EventViewer what key (code) is emitted when you press the mod4 key on your ergodox keyboard and then remap that key to `right_command`.

**Comment by julasamer** [comment]
How have I missed the Karabiner-EventViewer... that utility is super helpful. Turns out that my "mod4" key produced a not-us-backslash for some reason, so I just remapped that.
Everything works great once again! Thanks for the tips everyone!
