### ISSUE TITLE
Mapping Right-Option To Cmd

### ISSUE THREAD

**Issue by olbrichj** [jgosmann/Karabiner-Elements-Neo#12]
I'm used by the old layout to have right-option mapped to cmd.
Don't know if this is the default, but I think it is part of the official setup tutorial.
Maybe just add right_option to left_command in the README :)

**Comment by tjanson** [comment]
Yeah, you’re right, this is a good idea. Feel free to simply press the edit button on the README files’ pages and change it.
Otherwise I may do it later.

**Comment by jgosmann** [comment]
Fixed in 0202eafa76bd9f74c09a1313d7ad3112e0bdcc0d.
