### ISSUE TITLE
Neo only in certain programs working

### ISSUE THREAD

**Issue by linda4992** [jgosmann/Karabiner-Elements-Neo#14]
Hello,

I installed the Karabiner-Elements as described here. Luckily, I can use all 6 layers.

Unfortunately, neo only works in certain programs (Safari, Chrome, Finder, …) but not in others (Pages, TexStudio, Mail, …). Not working means that I cannot choose the neo-Keyboard as Input Source although it is displayed. 

However, I can use the arrow keys and the number pad of Layer 4 whenever I am in the standard German / English keyboard. The rest of Layer 4 works in neo,  provided neo is working.

I guess it cannot overwrite the application specific keybindings.
 

Thanks in advance!

Linda

**Comment by jgosmann** [comment]
In which directory did you install the `neo.keylayout` file?

**Comment by linda4992** [comment]
It is sitting in

/Library/Keyboard Layouts



On 27 Feb 2017, at 15:50, Jan Gosmann <notifications@github.com<mailto:notifications@github.com>> wrote:


In which directory did you install the neo.keylayout file?

**Comment by tjanson** [comment]
> Not working means that I cannot choose the neo-Keyboard as Input Source although it is displayed.

Just so we’re on the same page: You mean your input sources drop-down menu looks like this, but Neo is grayed out and can’t be selected?
Does it automatically switch to German when you enter the programs you mentioned?

<img width="267" alt="screen shot 2017-02-27 at 20 28 32" src="https://cloud.githubusercontent.com/assets/532114/23376244/c32666bc-fd2b-11e6-867a-74552b5454b6.png">

Do your keyboard settings look like this?

<img width="780" alt="screen shot 2017-02-27 at 20 31 42" src="https://cloud.githubusercontent.com/assets/532114/23376227/b7e2e280-fd2b-11e6-8304-7065c6fded55.png">

**Comment by linda4992** [comment]
Op 27 feb. 2017 om 20:47 heeft Tom Janson <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Not working means that I cannot choose the neo-Keyboard as Input Source although it is displayed.


Just so we’re on the same page: You mean your input sources drop-down menu looks like this, but Neo is grayed out and can’t be selected?
Does it automatically switch to German when you enter the programs you mentioned?

Yes. Sometimes it is grayed out, sometimes I just cannot click on it although it is not grayed out.


[screen shot 2017-02-27 at 20 28 32]<https://cloud.githubusercontent.com/assets/532114/23376244/c32666bc-fd2b-11e6-867a-74552b5454b6.png>

Do your keyboard settings look like this?

[screen shot 2017-02-27 at 20 31 42]<https://cloud.githubusercontent.com/assets/532114/23376227/b7e2e280-fd2b-11e6-8304-7065c6fded55.png>


Yes.

**Comment by tjanson** [comment]
Sounds like the issue isn’t specific to Neo; there are [many discussions in the Apple forums that sound similar](https://www.google.com/search?q=mac+os+keyboard+layout+grayed+out+site:discussions.apple.com) ([and elsewhere](https://apple.stackexchange.com/questions/225624/keyboard-layout-grayed-out)) (though I didn’t immediately see a solution).

Let me take two shots in the dark (based on some of the threads):

* Have you ever used an external Logitech keyboard on your Mac (and installed the related software)?
* Is your system language neither English nor German?

**Comment by linda4992** [comment]
Thank you very much for this advice.

Although I have never used any external keyboard (the Mac is brand-new) and although my system language in English, I do had Chinese as keyboard input method. After removing it and restarting I am able to use all 6 layers now.

Thanks a lot for your help!


On 27 Feb 2017, at 23:00, Tom Janson <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds like the issue isn’t specific to Neo; there are [many discussions in the Apple forums that sound similar] (though I didn’t immediately see a solution).

Let me take two shots in the dark (based on some of the threads):

  *   Have you ever used an external Logitech keyboard on your Mac (and installed the related software)?
  *   Is your system language neither English nor German?

**Comment by jgosmann** [comment]
That's great! 😃
