### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by HuskyNeo** [jgosmann/Karabiner-Elements-Neo#18]
Hi, ich weiß nicht ob ich was falsch gemacht habe, aber nachdem ich den MAKE Befehl ausführe kommt folgende Meldung

..............................................................** BUILD FAILED **

The following build commands failed:
	CompileC build/libkrbn.build/Release/libkrbn.build/Objects-normal/x86_64/libkrbn_system_preferences_monitor.o libkrbn_system_preferences_monitor.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[4]: *** [all] Error 65
make[3]: *** [all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2

make: *** [all] Error 99

Ich hoffe du hast eine Ahnung was das ist.
LG Husky

**Comment by tjanson** [comment]
Was ist die Ausgabe des Befehls `make -C src/apps/lib/libkrbn/ clean all`? (Am besten als [Gist](https://gist.github.com/) hochladen, ist vermutlich relativ lang.)

**Comment by HuskyNeo** [comment]
<script src="https://gist.github.com/HuskyNeo/b942993e2d1346e0dd691352d23178a1.js"></script> 

hoffe das passt so.

LG Liam

**Comment by HuskyNeo** [comment]
Soo erneuter versuch ^^ 

https://gist.github.com/HuskyNeo/b942993e2d1346e0dd691352d23178a1 

LG

**Comment by tjanson** [comment]
Boost ist nicht (oder nicht korrekt) installiert (siehe [Vorraussetzungen](https://github.com/jgosmann/Karabiner-Elements-Neo/wiki/Karabiner-Elements-Neo-selbst-bauen#voraussetzungen)). Falls du weitere Hilfe damit brauchst, sag Bescheid.

**Comment by HuskyNeo** [comment]
ja dank dir, es war wohl nicht erfolgreich installiert. Jetzt habe ich folgendes Problem, nach dem make Prozess wird mir folgendes angezeigt

https://gist.github.com/HuskyNeo/7f2dbd0562db79e859607042d32831c9

LG

**Comment by HuskyNeo** [comment]
dazu zu sagen ist aber noch dass alles zu funktionieren scheint.

LG

**Comment by jgosmann** [comment]
Die Ausgabe erscheint mir normal.

**Comment by tjanson** [comment]
Ja, wobei ein „Error“ sich natürlich besorgniserregend anhört. Ich hab daher in den Anleitungen einen entwarnenden Hinweis hinzugefügt.

**Comment by jgosmann** [comment]
Die Installationsanweisungen weisen inzwischen darauf hin, dass entsprechende Fehlermeldungen normal und kein Grund zur Sorge sind.

**Comment by crimsen** [comment]
Hey ... ich stehe heute vor dem selben Problem:
```
git clean -f -x -d
Removing pkginfo/Distribution.xml
Removing src/apps/EventViewer/Info.plist
Removing src/apps/EventViewer/build/
Removing src/apps/PreferencesWindow/PreferencesWindow/Info.plist
Removing src/apps/PreferencesWindow/build/
Removing src/apps/Updater/Updater/Info.plist
Removing src/apps/Updater/build/
Removing src/apps/lib/libkrbn/build/
Removing src/core/console_user_server/build/
Removing src/share/karabiner_version.h
Removing src/vendor/Karabiner-VirtualHIDDevice/src/Info.plist
./make-package.sh
make build
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
................** BUILD FAILED **


The following build commands failed:
	CompileC /Users/crimsen/git/Karabiner-Elements-Neo/src/core/console_user_server/build/karabiner_console_user_server.build/Release/karabiner_console_user_server.build/Objects-normal/x86_64/main.o /Users/crimsen/git/Karabiner-Elements-Neo/src/core/console_user_server/main.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[3]: *** [all] Error 65
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2

make: *** [all] Error 99
```

Ich bekomme jedoch bei dem Befehl `make -C src/apps/lib/libkrbn/ clean all` folgende [Ausgabe](https://gist.github.com/crimsen/224f561896aab667bc6a867912d8434c)

Ich bitte um Hilfe.

**Comment by jgosmann** [comment]
Die upstream Karabiner Elements-Version unterstützt Neo2 inzwischen. Bitte diese installieren.
