### ISSUE TITLE
ñ not possible with Compose

### ISSUE THREAD

**Issue by xlaech** [jgosmann/Karabiner-Elements-Neo#20]
I was told by the neo irc, that it should be possible to produce "ñ" as e.g. used in spanish using Compose:
`♫+~+n or`
`♫+n+~`

Unfortunately, this does not work atm. Is it possible to fix this?

**Comment by jgosmann** [comment]
Can you check whether the keyboard layout file in jgosmann/neo2-layout-osx#5 fixes the issue?

**Comment by jgosmann** [comment]
[Direct download link.](https://raw.githubusercontent.com/jgosmann/neo2-layout-osx/77d1b0ba19baea4cbe442d7d2d1f0411bedc7eeb/neo.keylayout)

**Comment by xlaech** [comment]
Thank you. It fixes the problem.
