### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by HuskyNeo** [jgosmann/Karabiner-Elements-Neo#21]
Hi, ich wollte gerade Neo2 auf meinem zweit Mac installieren und bekomme beim Ausführen von make folgende Fehlermeldung:

git clean -f -x -d
Removing pkginfo/Distribution.xml
Removing src/apps/EventViewer/Info.plist
Removing src/apps/PreferencesWindow/PreferencesWindow/Info.plist
Removing src/apps/Updater/Updater/Info.plist
Removing src/share/karabiner_version.h
Removing src/vendor/Karabiner-VirtualHIDDevice/src/Info.plist
./make-package.sh
make build
......xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make[4]: *** [all] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2

make: *** [all] Error 99

Vielen Dank schonmal für die Antwort,
Liebe Grüße Husky

**Comment by jgosmann** [comment]
Ist Xcode installiert?

**Comment by ThomasR** [comment]
Das tritt mit der neuen Xcode-Version auf. Man muss hier tatsächlich zunächst

    $ xcode-select -s [XCODE_PFAD]

 ausführen. Den korrekten Wert für `[XCODE_PFAD]` müsste ich im Büro nachschauen; ich glaube, es ist `/Applications/Xcode.app`.

**Comment by jgosmann** [comment]
Neo2 ist nun für die aktuelle upstream Karabiner-Elements Version implementiert.
Das heißt, es kann [das offizielle Karabiner-Elements](https://pqrs.org/osx/karabiner/) installiert werden und [die Neo2-Regeln lassen sich importieren](https://pqrs.org/osx/karabiner/complex_modifications/#neo2).
