### ISSUE TITLE
Mapping in README.md adds popout to menu bar

### ISSUE THREAD

**Issue by morremeyer** [jgosmann/Karabiner-Elements-Neo#24]
When I map the keys as described in the manual, each press of M3 (no matter if left or right) makes the "pop the window back and show the menu bar" effect. If I release it and press again before the zoom out effect fades, I can use Layer 3, but that's no long term solution.

Keyboard: internal, MacBook Air Early 2015 
MacOS Sierra 10.12.5 (16F73)

Any knowledge about that out there?

**Comment by tjanson** [comment]
Can you post a screenshot of what you are describing? Is this the Misson Control “App Exposé” view? (No, I guess not, since that actually hides the menu bar …)
Is it possible that you set up some keyboard shortcut for that view?

**Comment by morremeyer** [comment]
@tjanson I attached a screenshot for clarification. I don't think I have a keyboard shortcut set up - those are the system default right now.

It is not an issue with neo 2 itself as I can switch my Keyboard layout to qwertz and it still happens when pressing the `#` key.

![screenshot](https://user-images.githubusercontent.com/7683567/28877457-b5e54392-779c-11e7-9d80-55f07ef8e5dc.png)

**Comment by tjanson** [comment]
My guess is that you somehow have a keybinding set up for this, perhaps through some other third-party program. That’s the only guess I have, anyway — sorry.

If you want you can double-check your settings compared to mine (ignore the tab-to-control mapping):

<img width="912" alt="screen shot 2017-08-02 at 16 59 26" src="https://user-images.githubusercontent.com/532114/28880096-41b81bfe-77a4-11e7-899c-86aa4eac678b.png">

What you’re seeing is “App Exposé” a.k.a. “Mission Control Application windows”, which is triggered via gesture or keybord shortcut:

<img width="780" alt="screen shot 2017-08-02 at 16 56 23" src="https://user-images.githubusercontent.com/532114/28880124-58c559c4-77a4-11e7-8fd6-71ca66d70d14.png">
<img width="780" alt="screen shot 2017-08-02 at 17 03 30" src="https://user-images.githubusercontent.com/532114/28880188-8aee5af4-77a4-11e7-8877-36b45eab9ccc.png">

In this last screenshot you can see that I have it bound to Ctrl-DownArrow — I’m not sure if that’s the system default.

**Comment by morremeyer** [comment]
@tjanson Thanks for the detailed explanation, especially how that view is named! Deactivating the key combination there didn't help, but in System Settings -> Mission Control directly!

Thank you for pointing me in the right direction!

**Comment by tjanson** [comment]
Cool, glad I could help. :)
