### ISSUE TITLE
Mapping the "Application" key

### ISSUE THREAD

**Issue by morremeyer** [jgosmann/Karabiner-Elements-Neo#25]
In Karabiner, you can map the "Application" key many windows keyboards have. I use a Microsoft Sculpt Ergonomic Desktop which has this particular key and would like to map it to right option, but I can't find it in the source key drop down menu.

The same goes for the "<" and "^"-keys as MacOS is swapping them on my keyboard for whatsoever reason.

Is this not implemented or am I missing something?

**Comment by tjanson** [comment]
The Application key is there, you just need to scroll down quite a bit in the list. I’m not sure about `<` and `^`, maybe @jgosmann knows more?

By the way, it’s possible that you’ll run into more trouble when using an external keyboard — there’ve been reports of that in the past. (I tried to use one once — in fact I think it was also a Microsoft Sculpt Ergonomic Desktop — and couldn’t immediately get everything right.)

**Comment by jgosmann** [comment]
> I’m not sure about < and ^, maybe @jgosmann knows more?

You should be able to use Karabiner-EventViewer to figure out the names used by Karabiner to identify those keys.
