### ISSUE TITLE
Eingabe hängt

### ISSUE THREAD

**Issue by elbarto132** [jgosmann/Karabiner-Elements-Neo#26]
Ich nutze OSX Sierra.
Manchmal sind die Tastendrücke verzögert, es kommen für einige Sekunden (mal länger, mal kürzer) keine Tastendrücke an, auch z.B. Karabiner Eventviewer zeigt dann nichts an. Nach Ablauf dieser Zeit kommen dann aber alle Tastendrücke auf einmal.

Es betrifft sowohl die interne als auch eine externe Tastatur. Das Problem tritt während des Betriebs zufällig auf und vermehrt nachdem der Laptop im Standby war (aber nicht immer).
Ohne Karabiner Elements Neo scheint das Problem nicht aufzutreten.
Vermutlich das gleiche wie hier: https://github.com/tekezo/Karabiner-Elements/issues/502

Allerdings ist der Post schon etwas älter, ggf. löst die aktuelle Karabiner Elements Version das Problem auch schon. Ist geplant Karabiner Elements Neo auf die aktuelle Version zu updaten?

**Comment by jgosmann** [comment]
> Ist geplant Karabiner Elements Neo auf die aktuelle Version zu updaten?

Ja, ist geplant, aber bisher kann ich noch keine Prognose abgeben, wann ich dazu kommen werde.

**Comment by jgosmann** [comment]
Neo2 ist nun für die aktuelle upstream Karabiner-Elements Version implementiert.
Das heißt, es kann [das offizielle Karabiner-Elements](https://pqrs.org/osx/karabiner/) installiert werden und [die Neo2-Regeln lassen sich importieren](https://pqrs.org/osx/karabiner/complex_modifications/#neo2).
