### ISSUE TITLE
Provide German instructions.

### ISSUE THREAD

**Issue by jgosmann** [jgosmann/Karabiner-Elements-Neo#5]
- [x] README.md
- [x] Wiki page with build instructions

**Comment by tjanson** [comment]
I’ll start on this.

**Comment by tjanson** [comment]
[Here’s the Wiki page](https://github.com/jgosmann/Karabiner-Elements-Neo/wiki/Karabiner-Elements-Neo-selbst-bauen).

**Comment by jgosmann** [comment]
Thank you!
