### ISSUE TITLE
Minus on Layer 4

### ISSUE THREAD

**Issue by Marvin182** [jgosmann/Karabiner-Elements-Neo#8]
For be the layer 4 + ü wites the big ẞ instead of the minus sign.

This happens for both modifier keys, >/< (M4) and right cmd (Mod4). All other keys of layer 4 seem to work as expected.
Do you need any logs?

**Comment by jgosmann** [comment]
What keyboard layout file are you using? (The one provided from neo-layout.org or the one [provided here](https://github.com/jgosmann/neo2-layout-osx)?)

**Comment by Marvin182** [comment]
The one from neo-layout

**Comment by jgosmann** [comment]
Try the other one and see if that helps. (That is the one where it would be fixed anyways if it is not already.)

**Comment by tjanson** [comment]
It happens with both.

**Comment by jgosmann** [comment]
Try again [with this one](https://github.com/jgosmann/neo2-layout-osx) and see if it is fixed. You might need to restart your Mac after installing the new keyboard layout file.

**Comment by Marvin182** [comment]
now the minus on layer 4 works, but the shift is broken. trying to the Alphabet in upper case:
AbcdEfghIjklmNOpqrstUvwxYZ

(I did the restart.)

**Comment by jgosmann** [comment]
This should be working now. If not feel free to reopen this issue.
